[cutscene]

file = "assets/cutscenes/intro.mp4"
skippable = true

[menu]
font = "assets/fonts/scigoth.ttf"
background = "assets/menu/background.png"

start_message = "Start Game"
save_message = "Save Game"
load_message = "Load Game"
exit_message = "EXIT"

[[episode]]
title = "Minerva Base"

[[episode.maps]]
title = "Arrival"
file = "maps/episode01/map01.txt"

[[episode.maps]]
title = "Reactor"
file = "maps/episode01/map02.txt"

[[episode.maps]]
title = "Escape"
file = "maps/episode01/map03.txt"