[cutscene]

path = "assets/cutscenes/intro"

fps = 24

music = ""

skippable = true

[menu]
font = "assets/fonts/scigoth.ttf"
background = "assets/menu/background.png"
music = "assets/music/menu.mp3"

start_message = "Start Game"
save_message = "Save Game"
load_message = "Load Game"
exit_message = "EXIT"

[[episode]]
title = "Minerva Base"

[[episode.maps]]
title = "Arrival"
file = "maps/episode01/map01.txt"
music = "assets/music/map01.mp3"

[[episode.maps]]
title = "Reactor"
file = "maps/episode01/map02.txt"
music = "assets/music/map02.mp3"

[[episode.maps]]
title = "Escape"
file = "maps/episode01/map03.txt"
music = "assets/music/map03.mp3"